"""Write index-light.html: the deck, forced to its light palette.

The deck is already both themes. `:root` carries the light palette, and the
dark one is applied only by `@media (prefers-color-scheme: dark)` behind a
`:root:not([data-theme="light"])` guard. So a viewer whose machine is set to
dark mode gets a dark deck, which is usually right and is wrong on a bright
projector or in a PDF.

This writes a copy that sets `data-theme="light"` on the root element before
the first paint, which the guard above then honours whatever the machine
prefers. Nothing else differs: same markup, same CSS, same script.

    python presentation/make_light.py presentation/index.html \
        presentation/index-light.html

Run it again after any edit to index.html. The copy is generated, so edits made
to it directly are lost on the next run.

Two things are deliberately not done here. The copy gets no doctype, because
index.html has none and adding one would switch it from quirks mode to
standards mode and reflow the slides. And the attribute is set from a script in
the head rather than by adding an `<html>` tag, for the same reason: it leaves
parsing untouched.
"""

import sys
from pathlib import Path

ANCHOR = '<meta charset="utf-8">'

FORCE = """
<!-- Generated by make_light.py from index.html. Do not edit; rerun the script.
     Forces the light palette regardless of the viewer's dark-mode setting. -->
<script>document.documentElement.setAttribute('data-theme', 'light')</script>"""


def main() -> int:
    src, out = Path(sys.argv[1]), Path(sys.argv[2])
    html = src.read_text(encoding='utf-8')

    if ANCHOR not in html:
        print(f'{src}: no {ANCHOR!r} to anchor the theme switch to')
        return 1
    if 'make_light.py' in html:
        print(f'{src} is itself generated; pass the real deck instead')
        return 1

    html = html.replace(ANCHOR, ANCHOR + FORCE, 1)
    out.write_text(html, encoding='utf-8')
    print(f'wrote {out} ({len(html):,} bytes)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
